name: Tag repo
run-name: tag-workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    uses: org-test-reply-1/platform-action/tag-repo@main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
